spring.application.name=curation
newsapi.key=f747cecb3f28411386164ef023795eaa
newsapi.url=https://newsapi.org/v2/everything?q=AI%20OR%20인공지능&language=ko&from=2025-04-03&to=2025-04-10&sortBy=publishedAt&pageSize=100
newsapi.date.from=2025-01-01
newsapi.date.to=2025-04-01


# SQLite 데이터베이스 연결 설정
spring.datasource.url=jdbc:sqlite:src/main/resources/db/news.db
spring.datasource.driverClassName=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=
spring.jpa.database-platform=kr.ac.dankook.cs.curation.config.SQLiteDialect

# Hibernate 설정 (DDL 자동 생성)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
