spring.application.name=curation
newsapi.key=f747cecb3f28411386164ef023795eaa
newsapi.url=https://newsapi.org/v2/everything
#https://newsapi.org/v2/everything?q=AI OR 인공지능&language=ko&apiKey=f747cecb3f28411386164ef023795eaa

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:newsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
#https://newsapi.org/v2/everything?q=AI OR 인공지능&language=ko&apiKey=f747cecb3f28411386164ef023795eaa