spring.datasource.url=jdbc:mysql://localhost:3306/news_curation?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=Datajj04!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true

newsapi.key=f747cecb3f28411386164ef023795eaa
newsapi.url=https://newsapi.org/v2/everything